baseURL: "https://annaseogyeongchoi.github.io/" 
title: Anna Seo Gyeong Choi
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1 
        - name: Publications
          url: publications/
          weight: 2
        - name: About Me
          url: aboutme/
          weight: 3
        # - name: Courses
        #   url: courses/
        #   weight: 3
        # - name: Data
        #   url: data/
        #   weight: 4 
        # - name: Blog
        #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #   weight: 6

params:
    description: "This website hosts Anna Seo Gyeong Choi's research papers, curriculum vitae, and contact information."
    author: Anna Seo Gyeong Choi
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "September 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","papers", "aboutme"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Anna Seo Gyeong Choi
          subtitle: "Hi All! I’m Anna Seo Gyeong Choi. I’m currently a 5th-year Ph.D. candidate in Information Science at Cornell University, working with [Professor Allison Koenecke](https://koenecke.infosci.cornell.edu/). I work in the intersection between AI Ethics and Automatic Speech Recognition, with interests in Human-Computer Interaction in terms of Accessibility for populations with atypical speech. "
          imageUrl: "profile.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Publication
              url: publications/
            - name: About Me
              url: aboutme/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: Anna_Choi_CV.pdf
        - name: Email
          url: mailto:sc2359@cornell.edu
        - name: LinkedIn
          url: https://www.linkedin.com/in/csganna/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cGB8_a8AAAAJ&hl=en
        - name: GitHub
          url: https://github.com/AnnaSeoGyeongChoi
        - name: Twitter
          url: https://x.com/anna_sg_choi

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Anna Seo Gyeong Choi"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2