baseURL: "https://annaseogyeongchoi.github.io/" 
title: Anna Seo Gyeong Choi
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 5 
        - name: Publications
          url: publications/
          weight: 2
        - name: Education
          url: education/
          weight: 3
        # - name: Courses
        #   url: courses/
        #   weight: 3
        # - name: Data
        #   url: data/
        #   weight: 4 
        # - name: Blog
        #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #   weight: 6

params:
    description: "This website hosts Anna Seo Gyeong Choi's research papers, curriculum vitae, and contact information."
    author: Anna Seo Gyeong Choi
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "September 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","papers", "education"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Anna Seo Gyeong Choi
          subtitle: "Hi All! I’m Anna Seo Gyeong Choi. My Korean name is 최서경, but you can call me Anna! I’m currently a 5th-year Ph.D. candidate in Information Science at Cornell University, working with [Professor Allison Koenecke](https://koenecke.infosci.cornell.edu/). I started out my Ph.D. journey in the Linguistics Department, where I mostly worked with Professor Mats Rooth and Professor Sam Tilsen, and then transferred at the end of my 2nd year to Information Science. I still keep ties with the Linguistics by working for a minor degree. I’m currently affiliated with University of Pennsylvania as a Visiting Scholar at Linguistic Data Consortium, working with [Professor Sunghye Cho](https://www.sunghyecho.com/home). I work in the intersection between AI Ethics and Automatic Speech Recognition, with interests in Human-Computer Interaction in terms of Accessibility for populations with atypical speech. I have two main research interests: **(1) Auditing Speech-to-Text algorithms** and **(2) Using voice as a biomarker in AI for Healthcare**. I work with diverse speech datasets to test for algorithmic fairness in ASR models and critique evaluation methods, both in terms of the technical aspect and the social and legal aspect. Because I work with speech data from people with health impairments, I analyze their acoustic features in an attempt to utilize voice as a biometric. I focus on diagnosis of their state in terms of severity, especially focusing on neurodegenerative disorders such as Alzheimer’s Disease, Schizophrenia, and Aphasia, among many others. Combining the two, I’m interested in increasing accessibility for these populations, such as working on transcription output styles."
          imageUrl: "profile.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Publication
              url: publications/
            - name: Education
              url: education/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: Anna_Choi_CV.pdf
        - name: Email
          url: mailto:sc2359@cornell.edu
        - name: LinkedIn
          url: https://www.linkedin.com/in/csganna/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cGB8_a8AAAAJ&hl=en
        - name: GitHub
          url: https://github.com/AnnaSeoGyeongChoi
        - name: Twitter
          url: https://x.com/anna_sg_choi

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Anna Seo Gyeong Choi"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2